cuthill-Mckee法の計算結果のREADMEへの追加
fixstars/AlgebraicBlockMulticolorOrdering pull request #12
Opened 2018-03-22 09:53 UTC by kurenaif

2018-03-22 09:54 UTC, kurenaif commented
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/tree/doc-cuthill-mckee
READMEはこちらを参照してください。
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/issues/1

2018-03-22 10:00 UTC, LWisteria commented
abmc.ods忘れてません？

2018-03-22 10:04 UTC, LWisteria commented
あと、CMのSymGSが消えている気がします。

2018-03-22 10:05 UTC, LWisteria requested changes
レビューしました（バイナリファイルにレビューコメント付けられなかったので（付けられる？、普通にコメントにしました）

2018-03-23 01:23 UTC, kurenaif commented
READMEの修正をしました
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/tree/doc-cuthill-mckee

- [x] Abmc.odsにcuthillmckeeシートの追加
- [x] iteration.odsのCuthillMckeeのSymGSの位置が不適切だった問題を解消

レビューよろしくおねがいします！

2018-03-23 02:01 UTC, merged

2018-03-23 02:01 UTC, LWisteria commented
LGTM