(同じレベル内での隣接ノードを考慮しない)cuthill-mckee法の実装を行いました。
fixstars/AlgebraicBlockMulticolorOrdering pull request #4
Opened 2018-03-20 06:27 UTC by kurenaif

https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/issues/1
こちらに書いてある実装方法で、まず隣接ノードを考慮しないcuthill-mckee法を実装しました。

並列化のためには、同じレベル内で隣接ノードを排除しなければなりませんが、現状それは実装していません。

2018-03-20 06:52 UTC, LWisteria commented
@kurenaif 期待される出力を貼ってもらえますか？

2018-03-20 06:54 UTC, kurenaif commented
出力とは収束の様子でしょうか？

2018-03-20 06:55 UTC, LWisteria commented
はい、正しく動いていることを示すようなものです。

2018-03-20 07:19 UTC, LWisteria requested changes
レビューしました

2018-03-20 07:19 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		const Index index = degreeIndex[i].second;
これ使ってませんね？

2018-03-20 07:19 UTC, LWisteria commented on Abmc/SymGS.hpp
> +// CutHill-Mckeeのガウスザイデル法
細かいですが、Cuthillです（hは小文字

他にも同様の表現があるので直しておいてください

2018-03-20 07:33 UTC, kurenaif commented
現状のものを貼っておきます
```
row[0]:0 (level: 1)
row[1]:1 (level: 2)
row[2]:8 (level: 2)
row[3]:9 (level: 2)
row[4]:2 (level: 3)
row[5]:10 (level: 3)
row[6]:16 (level: 3)
row[7]:17 (level: 3)
row[8]:18 (level: 3)
row[9]:3 (level: 4)
row[10]:11 (level: 4)
row[11]:19 (level: 4)
row[12]:24 (level: 4)
row[13]:25 (level: 4)
row[14]:26 (level: 4)
row[15]:27 (level: 4)
row[16]:4 (level: 5)
row[17]:12 (level: 5)
row[18]:20 (level: 5)
row[19]:28 (level: 5)
row[20]:32 (level: 5)
row[21]:33 (level: 5)
row[22]:34 (level: 5)
row[23]:35 (level: 5)
row[24]:36 (level: 5)
row[25]:5 (level: 6)
row[26]:13 (level: 6)
row[27]:21 (level: 6)
row[28]:29 (level: 6)
row[29]:37 (level: 6)
row[30]:40 (level: 6)
row[31]:41 (level: 6)
row[32]:42 (level: 6)
row[33]:43 (level: 6)
row[34]:44 (level: 6)
row[35]:45 (level: 6)
row[36]:6 (level: 7)
row[37]:14 (level: 7)
row[38]:22 (level: 7)
row[39]:30 (level: 7)
row[40]:38 (level: 7)
row[41]:46 (level: 7)
row[42]:48 (level: 7)
row[43]:49 (level: 7)
row[44]:50 (level: 7)
row[45]:51 (level: 7)
row[46]:52 (level: 7)
row[47]:53 (level: 7)
row[48]:54 (level: 7)
row[49]:7 (level: 8)
row[50]:15 (level: 8)
row[51]:23 (level: 8)
row[52]:31 (level: 8)
row[53]:39 (level: 8)
row[54]:47 (level: 8)
row[55]:55 (level: 8)
row[56]:56 (level: 8)
row[57]:57 (level: 8)
row[58]:58 (level: 8)
row[59]:59 (level: 8)
row[60]:60 (level: 8)
row[61]:61 (level: 8)
row[62]:62 (level: 8)
row[63]:63 (level: 8)
offset[0]:0
offset[1]:1
offset[2]:4
offset[3]:9
offset[4]:16
offset[5]:25
offset[6]:36
offset[7]:49
offset[8]:64
```
このようにmapしていて、
収束結果は
```
+++++++++++++++++++++
CutHill-Mckeeガウスザイデル法
0, 641281
1, 395383
2, 273989
3, 193899
4, 137629
5, 97472.1
6, 68801.4
7, 48402.1
8, 33947.4
9, 23745.7
10, 16572
11, 11543.8
12, 8029.11
13, 5577.85
14, 3871.35
15, 2685.01
16, 1861.19
17, 1289.6
18, 893.268
19, 618.592
20, 428.3
21, 296.506
22, 205.245
23, 142.063
24, 98.3244
25, 68.0493
26, 47.0947
27, 32.5919
28, 22.5548
29, 15.6085
30, 10.8014
31, 7.47473
32, 5.17259
33, 3.57947
34, 2.47701
35, 1.7141
36, 1.18616
37, 0.820825
38, 0.568011
39, 0.393063
40, 0.272
41, 0.188223
42, 0.13025
43, 0.0901331
44, 0.062372
45, 0.0431613
46, 0.0298675
47, 0.0206683
48, 0.0143024
49, 0.00989725
50, 0.00684888
51, 0.00473941
52, 0.00327966
53, 0.00226952
54, 0.0015705
55, 0.00108679
56, 0.000752053
57, 0.000520419
58, 0.000360129
59, 0.000249209
60, 0.000172452
61, 0.000119336
62, 8.25806e-05
63, 5.71456e-05
64, 3.95446e-05 (参考: そのままのガウスザイデル法: 64, 3.58829e-05)
+++++++++++++++++++++
CutHill-Mckee対称ガウスザイデル法
0, 641281
1, 266338
2, 133737
3, 68586.9
4, 35284.8
5, 18163.9
6, 9351.9
7, 4815.11
8, 2479.21
9, 1276.48
10, 657.222
11, 338.38
12, 174.218
13, 89.6976
14, 46.1813
15, 23.7766
16, 12.2415
17, 6.30256
18, 3.24488
19, 1.67063
20, 0.860128
21, 0.442838
22, 0.227996
23, 0.117384
24, 0.0604353
25, 0.0311152
26, 0.0160197
27, 0.00824775
28, 0.00424637
29, 0.00218625
30, 0.00112559
31, 0.000579512
32, 0.000298362
33, 0.000153612
34, 7.90874e-05
35, 4.07182e-05
36, 2.09638e-05
37, 1.07933e-05
38, 5.55692e-06
39, 2.86099e-06
40, 1.47298e-06
41, 7.58366e-07
42, 3.90446e-07
43, 2.01021e-07
44, 1.03496e-07
45, 5.32851e-08
46, 2.74339e-08
47, 1.41244e-08
48, 7.27195e-09
49, 3.74397e-09
50, 1.92759e-09
51, 9.92421e-10
52, 5.10949e-10
53, 2.63063e-10
54, 1.35438e-10
55, 6.97304e-11
56, 3.59008e-11
57, 1.84836e-11
58, 9.51629e-12
59, 4.89947e-12
60, 2.5225e-12
61, 1.29871e-12
62, 6.68643e-13
63, 3.44252e-13
64, 1.77239e-13 (参考: そのままの対照ガウスザイデル法: 64, 64, 9.09935e-14)
####################################
```
となっています。

2018-03-20 07:52 UTC, LWisteria requested changes
追加でレビューしました（まだ途中ですが

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	for (Index i = decltype(N)(0); i < N; i++)
Indexと宣言してキャスト（するかもしれない）ようにするよりはautoにしといていいですよね

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	for (Index i = decltype(N)(0); i < N; i++)
同様の箇所もあるので見直しておいてください

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	Level maxLevel = Level(0);
ここもautoでいいはず

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	auto level = std::make_unique<Level[]>(N);
↓でINVALID_LEVEL(0)で初期化されていることを想定しているところがありますが、make_uniqueで初期化されるのは`Level()`で、0かどうか（Levelがどんな型かは知らないと）はっきりしないので、明示的にfillするか、INVALID_LEVELの定義を変えたほうがいいですね。

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		for (Index i = decltype(N)(0); i < N; i++)
ここ、foreachで良くないですか？（iを他の用途で使ってないので

2018-03-20 07:52 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		const auto deg = A.index1_data()[i] - offset; // count
ここ、[i+1]じゃないですか？

2018-03-20 08:15 UTC, LWisteria requested changes
とりあえずCuthillMckee()の中はざっとレビューしました

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		Index minDegreeIndex = N + 1;
N+1でもいいんですが、indexの最大値はN-1（なぜならN個しかないので）で、Nでいいと思うのですが、+1した理由はなにかありますか？

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		for (auto cur = que.front(); !que.empty(); que.pop()) {
{の位置

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		// cur: 今見ているノード
参考資料の表記が「点」で統一されていて↑までもそうだったので、「ノード」じゃなくて「点」にしときましょう

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +				const auto tar = A.index2_data()[offset + idx];
ここ、他のところに合わせるなら列番号jですよね？独自の名前じゃなくてそっちに合わせておいたほうがいいと思います。

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		auto offset = std::make_unique<Index[]>(maxLevel+1); // 各色の開始番号
色じゃないですね、レベル？

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		for (auto cur = que.front(); !que.empty(); que.pop()) {
あと、curも行番号iとしておいたほうがいいですね。

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +					// level[tar]は常にmaxLevelを指す
ここ、先にmaxLevelを設定して、level[j]=maxLevelにすればコメントなくてもわかりやすくなりませんか？

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +					level[tar] = level[cur] + 1;
level配列を中でいじっていることを考えると、コンパイラ的なのを可読性を考えて、level[cur]はcur=que.front()の直後ぐらいにで読んでおいて固定したほうがいいです

2018-03-20 08:15 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		for (auto cur = que.front(); !que.empty(); que.pop()) {
よく考えたら直後でfront()することを考えたらここで初期値取る必要ないですね（むしろ変数がループごとに使い回さないといけなくなってしんどい）

2018-03-20 08:43 UTC, LWisteria requested changes
CreateRowForCuthillMckee()をレビューしました

2018-03-20 08:43 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		SymmetryGaussSeidelForCutHillMckee(A,b,expect, row.get(), offset.get(), maxLevel);
さっき口頭でも指摘しましたけど、ここでガウスザイデル法とかを解くのはおかしいですね。独立した島があったら、とりあえずレベルを+1すれば済むと思います。

2018-03-20 08:43 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	// ・同じブロックなら行番号の小さい順
色とかブロックとか使ってないものばかりなので（↓のコード中も）正しく合わせておいてください

2018-03-20 08:43 UTC, LWisteria commented on Abmc/Abmc.hpp
> +static void CreateRowForCuthillMckee(Index row[], Index offset[], const Level level[], const Level degree[])
degreeの型はIndexでは

2018-03-20 08:43 UTC, LWisteria commented on Abmc/Abmc.hpp
> +			const auto leftBlock = std::get<1>(left); const auto rightBlock = std::get<1>(right);
次数が小さいものを優先的に先頭にする意味ってあります？

2018-03-20 08:43 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		CreateRowForCuthillMckee(row.get(), offset.get(), level.get(), degree.get());
元のCreateRow()を真似たのだと思いますが、向こうは複数箇所から呼ばれているので関数になっているだけで、こちらは特にないと思うので、ここに直に書いていいと思います

2018-03-20 08:46 UTC, kurenaif commented on Abmc/Abmc.hpp
> +		Index minDegreeIndex = N + 1;
`N`でも問題ないのはわかった上で、`N+1`を採用しました。
`N`は配列外だと思うのに少し時間がかかる(配列外参照ガードのために配列を拡張するなどの実装が時々あるため)のですが、`N+1`なら明らかに配列外だということが直感的にわかりやすいかなと思い、そうしました
少なくとも自分は`N`と見たときに一瞬悩みました

2018-03-20 08:53 UTC, kurenaif commented on Abmc/Abmc.hpp
> +			const auto leftBlock = std::get<1>(left); const auto rightBlock = std::get<1>(right);
次数が少ない順にすることは参考資料に書いてありました。
並列計算を考慮しないCM法の場合、次数が少ない順に計算することでincompatible nodeの数を少なくしようとしているものだと思っています

2018-03-20 09:06 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		Index minDegreeIndex = N + 1;
うーんなるほど・・・？ただ、Nが最大値だと+1した時にオーバーフローするので、特に意味がないのであればやらないほうがいいかと思います。

あるいはいっそここをnumeric_limits::maxにするとか

2018-03-20 09:09 UTC, LWisteria commented on Abmc/Abmc.hpp
> +			const auto leftBlock = std::get<1>(left); const auto rightBlock = std::get<1>(right);
あぁ、確かに書いてありますね。

了解です。名前とかだけ直してくださいね。

2018-03-20 09:40 UTC, kurenaif commented on Abmc/Abmc.hpp
> +		for (Index i = decltype(N)(0); i < N; i++)
`degreeIndex` は unique_ptrで作っているので、base ranged for(for(:))は使えないです。
std::for_each()もbreakをする必要がありうまく実装ができません。

std::find_if()を使用すると、最初の要素を発見してくれるので、これを使うことにします。

2018-03-20 09:50 UTC, kurenaif commented on Abmc/Abmc.hpp
> +		Index minDegreeIndex = N + 1;
numeric_limits::maxは思いつきませんでした！
ここの実装をstd::find_ifに書き換えたので、それに伴い判定方法も変わりました。(ポインタがdegreeIndex.get()+Nになったら終了)

2018-03-22 01:54 UTC, kurenaif commented on Abmc/Abmc.hpp
> +		CreateRowForCuthillMckee(row.get(), offset.get(), level.get(), degree.get());
同じレベル内での隣接ノードを考慮しないCuthill-Mckeeと, 同じレベル内での隣接ノードを考慮するCuthill-Mckeeの関数を両方残そうと考えていて、2つ実装した際に `CreateRowForCuthillMckee` を2度呼ぶ必要があるのですが、それでも分けたほうがよいでしょうか？

2018-03-22 03:19 UTC, kurenaif commented
斜めを含む9点ステンシルでの
cuthill-Mckeeで更新する順番を二次元平面上で表現してみました(次元が必ず0になるバグは修正済み)
```
00 01 04 09 16 25 36 49 
02 03 06 11 18 27 38 52 
05 07 08 12 19 28 39 53 
10 13 14 15 20 29 40 54 
17 21 22 23 24 30 41 55 
26 31 32 33 34 35 42 56 
37 43 44 45 46 47 48 57 
50 58 59 60 61 62 63 51 
```
levelのoffsetは
```
0,1,4,9,16,25,36,49,64
```
です。(左上から正方形が広がるようにlevelが増えていきます)
例えば、`03` を見るときに、普通のガウスザイデルでは `04` はすでに計算済みですが、cuthill-Mckeeでは更新されていません。

斜めを含まない5点ステンシルでの計算もやってみたところ
```
00 01 03 06 10 15 21 28 
02 05 08 12 17 23 30 36 
04 09 13 18 24 31 38 43 
07 14 19 25 32 39 45 49 
11 20 26 33 40 46 51 54 
16 27 34 41 47 52 56 58 
22 35 42 48 53 57 60 61 
29 37 44 50 55 59 62 63 
```
このように更新されていました。
offsetは
```
0,1,3,6,10,15,21,28,36,43,49,54,58,61,63,64
```
このケースでは、普通のガウスザイデルと同じ箇所が更新されているので、結果が一緒になるはずです。実際に結果を見ると、
```
反復回数, ガウスザイデル, cuthill-mckee ガウスザイデル
0, 641281.0, 641281.0, 
1, 433821.0, 433821.0, 
2, 324794.0, 324794.0, 
3, 250965.0, 250965.0, 
4, 196391.0, 196391.0, 
5, 154523.0, 154523.0, 
6, 121849.0, 121849.0, 
7, 96142.4, 96142.4, 
8, 75843.7, 75843.7, 
9, 59791.1, 59791.1, 
10, 47093.2, 47093.2, 
11, 37053.8, 37053.8, 
12, 29123.9, 29123.9, 
13, 22867.4, 22867.4, 
14, 17937.7, 17937.7, 
15, 14058.3, 14058.3, 
16, 11009.3, 11009.3, 
17, 8615.73, 8615.73, 
18, 6738.55, 6738.55, 
19, 5267.71, 5267.71, 
20, 4116.15, 4116.15, 
21, 3215.17, 3215.17, 
22, 2510.65, 2510.65, 
23, 1960.01, 1960.01, 
24, 1529.81, 1529.81, 
25, 1193.83, 1193.83, 
26, 931.506, 931.506, 
27, 726.734, 726.734, 
28, 566.921, 566.921, 
29, 442.215, 442.215, 
30, 344.918, 344.918, 
31, 269.013, 269.013, 
32, 209.802, 209.802, 
33, 163.618, 163.618, 
34, 127.596, 127.596, 
35, 99.5027, 99.5027, 
36, 77.5928, 77.5928, 
37, 60.5063, 60.5063, 
38, 47.1817, 47.1817, 
39, 36.7909, 36.7909, 
40, 28.6882, 28.6882, 
41, 22.3699, 22.3699, 
42, 17.443, 17.443, 
43, 13.6011, 13.6011, 
44, 10.6054, 10.6054, 
45, 8.26949, 8.26949, 
46, 6.44804, 6.44804, 
47, 5.02778, 5.02778, 
48, 3.92034, 3.92034, 
49, 3.05683, 3.05683, 
50, 2.38351, 2.38351, 
51, 1.8585, 1.8585, 
52, 1.44913, 1.44913, 
53, 1.12993, 1.12993, 
54, 0.881043, 0.881043, 
55, 0.686976, 0.686976, 
56, 0.535656, 0.535656, 
57, 0.417667, 0.417667, 
58, 0.325667, 0.325667, 
59, 0.253932, 0.253932, 
60, 0.197998, 0.197998, 
61, 0.154385, 0.154385, 
62, 0.120378, 0.120378, 
63, 0.0938624, 0.0938624, 
64, 0.0731872, 0.0731872, 
```
と問題なさそうでした。対照ガウスザイデル法に関しては、
```
反復回数, 対照ガウスザイデル, cuthill-mckee 対照ガウスザイデル
0, 641281.0, 641281.0, 
1, 325339.0, 327398.0, 
2, 197579.0, 197869.0, 
3, 123339.0, 123420.0, 
4, 77514.4, 77547.8, 
5, 48809.2, 48826.1, 
6, 30754.3, 30763.8, 
7, 19383.2, 19388.9, 
8, 12218.0, 12221.5, 
9, 7701.94, 7704.09, 
10, 4855.29, 4856.64, 
11, 3060.82, 3061.66, 
12, 1929.59, 1930.12, 
13, 1216.44, 1216.78, 
14, 766.87, 767.082, 
15, 483.45, 483.584, 
16, 304.777, 304.861, 
17, 192.138, 192.191, 
18, 121.127, 121.161, 
19, 76.3611, 76.3823, 
20, 48.1396, 48.1529, 
21, 30.3482, 30.3566, 
22, 19.1321, 19.1374, 
23, 12.0613, 12.0646, 
24, 7.60365, 7.60576, 
25, 4.79349, 4.79482, 
26, 3.02191, 3.02275, 
27, 1.90507, 1.9056, 
28, 1.201, 1.20133, 
29, 0.757132, 0.757341, 
30, 0.477311, 0.477443, 
31, 0.300906, 0.300989, 
32, 0.189697, 0.18975, 
33, 0.119589, 0.119622, 
34, 0.0753911, 0.075412, 
35, 0.0475281, 0.0475412, 
36, 0.0299626, 0.0299709, 
37, 0.018889, 0.0188943, 
38, 0.011908, 0.0119113, 
39, 0.00750705, 0.00750912, 
40, 0.00473259, 0.0047339, 
41, 0.00298352, 0.00298434, 
42, 0.00188087, 0.00188139, 
43, 0.00118574, 0.00118606, 
44, 0.000747512, 0.000747719, 
45, 0.000471246, 0.000471377, 
46, 0.000297083, 0.000297165, 
47, 0.000187287, 0.000187339, 
48, 0.000118069, 0.000118102, 
49, 7.44332e-05, 7.44538e-05, 
50, 4.69242e-05, 4.69372e-05, 
51, 2.95819e-05, 2.95901e-05, 
52, 1.8649e-05, 1.86542e-05, 
53, 1.17567e-05, 1.176e-05, 
54, 7.41166e-06, 7.41371e-06, 
55, 4.67246e-06, 4.67375e-06, 
56, 2.94561e-06, 2.94643e-06, 
57, 1.85697e-06, 1.85748e-06, 
58, 1.17067e-06, 1.17099e-06, 
59, 7.38014e-07, 7.38218e-07, 
60, 4.65258e-07, 4.65387e-07, 
61, 2.93308e-07, 2.93389e-07, 
62, 1.84907e-07, 1.84958e-07, 
63, 1.16569e-07, 1.16601e-07, 
64, 7.34875e-08, 7.35078e-08, 
```
と差がある結果になっているのが気になります。

2018-03-22 03:33 UTC, LWisteria commented
結果が多少ズレるのは、fmaの有無とかでありうるので、そこまで合っているなら問題ないと思います。

2018-03-22 03:34 UTC, LWisteria commented
あと、細かいですが、対照じゃなくて対象ですね。意味違ってくるのでお気をつけを。

2018-03-22 03:35 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		CreateRowForCuthillMckee(row.get(), offset.get(), level.get(), degree.get());
隣接ノードを考慮しないCMにあまり意味はないので、残さなくていいと思います。ので、関数も展開しておいてください。

2018-03-22 03:37 UTC, kurenaif commented
アッすみません気を付けます
対照でもなく対象でもなく対称ではないですか？
[参考](http://proc-cpuinfo.fixstars.com/2016/07/blog-post-html/)

2018-03-22 03:39 UTC, kurenaif commented on Abmc/Abmc.hpp
> +		CreateRowForCuthillMckee(row.get(), offset.get(), level.get(), degree.get());
了解しました。それを修正した上でもう一度pushします。

2018-03-22 03:56 UTC, LWisteria requested changes
再レビューしました

2018-03-22 03:56 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		auto minDegreeIndexItr = std::find_if(degreeIndex.get(), degreeIndex.get() + N, [&level, &INVALID_LEVEL](const auto& degIndex)
INVALID_LEVELを参照キャプチャする意味とは・・・（コピーでいいのでは

2018-03-22 03:56 UTC, LWisteria commented on Abmc/Abmc.hpp
> +		auto minDegreeIndexItr = std::find_if(degreeIndex.get(), degreeIndex.get() + N, [&level, &INVALID_LEVEL](const auto& degIndex)
あと、参照キャプチャする場合、その値を変えないのであれば、初期化ラムダを使って、constをつけておくのが望ましいです。例： https://wandbox.org/permlink/EtgAfa7SOxRd91Ds

2018-03-22 03:56 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	maxLevel--; //最後のqueが読まれたタイミングでmaxLevelが1大きくなるためここで減らす
これ、ループの中じゃないですか？

2018-03-22 03:56 UTC, LWisteria commented on Abmc/Abmc.hpp
> +	// 2. 幅優先探索 O(N)
ここに「幅優先探索」とあると、一番外側のループが幅優先探索の本体に読めてしまいますね。

ここは繋がっていない点がある場合に対する処理だと思うので、そんな感じにコメントを変えておいたほうが良さそうです。

2018-03-22 03:57 UTC, LWisteria commented
あう・・・私も誤変換していた・・・対称です。

2018-03-22 05:13 UTC, kurenaif commented on Abmc/Abmc.hpp
> +	maxLevel--; //最後のqueが読まれたタイミングでmaxLevelが1大きくなるためここで減らす
ループの中ですね… 実際に対角行列で動かして確認してみました ありがとうございます

2018-03-22 05:39 UTC, LWisteria approved these changes

2018-03-22 05:39 UTC, merged

2018-03-22 05:40 UTC, LWisteria commented
LGTM!

2018-03-22 05:41 UTC, kurenaif commented
マージありがとうございます！申し訳ないのですが、ミスって `apply_vs2017` にbase生やしちゃったので `master` で貼り直しても大丈夫ですか…?

2018-03-22 05:42 UTC, LWisteria commented
oh...気づいてなかったすみません。

masterで出し直してください。

2018-03-22 05:44 UTC, kurenaif commented
https://github.com/fixstars/AlgebraicBlockMulticolorOrdering/pull/10
こちらで貼り直しました。